# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBXT3VU4UTvuAjmMeXw4XVoA52tPjIdo
"""

score_list=input().split( )
count=0
for i in score_list:
  if int(i) <60:
    count+=1
print(count)